
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package midik.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVISION = 73;
  public static final int MENOR_IGUAL = 39;
  public static final int MENOR_QUE = 42;
  public static final int CONTINUAR = 20;
  public static final int MENSAJE = 27;
  public static final int ASC_ORD = 69;
  public static final int VERDADERO = 61;
  public static final int DESC_ORD = 65;
  public static final int CADENA_VAL = 58;
  public static final int SI = 11;
  public static final int KEEP = 8;
  public static final int DIFERENTE = 43;
  public static final int POT = 52;
  public static final int IMP_ORD = 67;
  public static final int POR = 72;
  public static final int FALSO = 62;
  public static final int MAYOR_QUE = 41;
  public static final int PISTA = 64;
  public static final int LONGITUD = 26;
  public static final int NOT = 47;
  public static final int CORCHETE_C = 60;
  public static final int NOR = 49;
  public static final int ORDENAR = 24;
  public static final int CORCHETE_A = 59;
  public static final int VAR = 9;
  public static final int DOS_PUNTOS = 32;
  public static final int LLAVE_C = 34;
  public static final int LLAVE_A = 33;
  public static final int SALIR = 15;
  public static final int HACER = 19;
  public static final int PARA = 17;
  public static final int MOD = 51;
  public static final int INCREMENTO = 53;
  public static final int COMA = 31;
  public static final int ENTERO = 3;
  public static final int DOBLE = 4;
  public static final int IGUAL = 37;
  public static final int BOOLEAN = 5;
  public static final int SWITCH = 13;
  public static final int DECREMENTO = 54;
  public static final int MENOS = 71;
  public static final int MAS = 70;
  public static final int PARENTESIS_C = 36;
  public static final int PARENTESIS_A = 35;
  public static final int DOBLE_VAL = 57;
  public static final int ARREGLO = 10;
  public static final int IS_NULL = 44;
  public static final int EOF = 0;
  public static final int MIENTRAS = 18;
  public static final int PUNTO = 30;
  public static final int DEFAULT = 16;
  public static final int SUMARIZAR = 25;
  public static final int CARACTER = 6;
  public static final int ENTERO_VAL = 56;
  public static final int PRINCIPAL = 28;
  public static final int OR = 46;
  public static final int error = 1;
  public static final int REPRODUCIR = 22;
  public static final int ID = 55;
  public static final int SINO = 12;
  public static final int EXTIENDE = 2;
  public static final int PAR_ORD = 66;
  public static final int CASO = 14;
  public static final int ESPERAR = 23;
  public static final int RETORNA = 21;
  public static final int ASIGNACION = 40;
  public static final int CADENA = 7;
  public static final int AND = 45;
  public static final int CARACTER_VAL = 63;
  public static final int PRIM_ORD = 68;
  public static final int P_COMA = 29;
  public static final int MAYOR_IGUAL = 38;
  public static final int NAND = 48;
  public static final int XOR = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXTIENDE",
  "ENTERO",
  "DOBLE",
  "BOOLEAN",
  "CARACTER",
  "CADENA",
  "KEEP",
  "VAR",
  "ARREGLO",
  "SI",
  "SINO",
  "SWITCH",
  "CASO",
  "SALIR",
  "DEFAULT",
  "PARA",
  "MIENTRAS",
  "HACER",
  "CONTINUAR",
  "RETORNA",
  "REPRODUCIR",
  "ESPERAR",
  "ORDENAR",
  "SUMARIZAR",
  "LONGITUD",
  "MENSAJE",
  "PRINCIPAL",
  "P_COMA",
  "PUNTO",
  "COMA",
  "DOS_PUNTOS",
  "LLAVE_A",
  "LLAVE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "IGUAL",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "ASIGNACION",
  "MAYOR_QUE",
  "MENOR_QUE",
  "DIFERENTE",
  "IS_NULL",
  "AND",
  "OR",
  "NOT",
  "NAND",
  "NOR",
  "XOR",
  "MOD",
  "POT",
  "INCREMENTO",
  "DECREMENTO",
  "ID",
  "ENTERO_VAL",
  "DOBLE_VAL",
  "CADENA_VAL",
  "CORCHETE_A",
  "CORCHETE_C",
  "VERDADERO",
  "FALSO",
  "CARACTER_VAL",
  "PISTA",
  "DESC_ORD",
  "PAR_ORD",
  "IMP_ORD",
  "PRIM_ORD",
  "ASC_ORD",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION"
  };
}

