
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package midik.analizadoresRecibirCancion.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SOLICITUD_A = 2;
  public static final int MENOR = 30;
  public static final int FAS = 22;
  public static final int RES = 19;
  public static final int DIAG = 31;
  public static final int OCTAVA_C = 14;
  public static final int SOLS = 24;
  public static final int OCTAVA_A = 7;
  public static final int SOL = 23;
  public static final int SILENCIO = 28;
  public static final int DURACION_C = 15;
  public static final int ID = 33;
  public static final int LAS = 26;
  public static final int DURACION_A = 8;
  public static final int FA = 21;
  public static final int RE = 18;
  public static final int DO = 16;
  public static final int LA = 25;
  public static final int NOTA_C = 13;
  public static final int NUMEROS = 32;
  public static final int MAYOR = 29;
  public static final int EOF = 0;
  public static final int NOTA_A = 6;
  public static final int MI = 20;
  public static final int SI = 27;
  public static final int error = 1;
  public static final int CANAL_C = 12;
  public static final int DOS = 17;
  public static final int TIPO_C = 10;
  public static final int CANAL_A = 5;
  public static final int TIPO_A = 3;
  public static final int DATOS_C = 11;
  public static final int DATOS_A = 4;
  public static final int SOLICITUD_C = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOLICITUD_A",
  "TIPO_A",
  "DATOS_A",
  "CANAL_A",
  "NOTA_A",
  "OCTAVA_A",
  "DURACION_A",
  "SOLICITUD_C",
  "TIPO_C",
  "DATOS_C",
  "CANAL_C",
  "NOTA_C",
  "OCTAVA_C",
  "DURACION_C",
  "DO",
  "DOS",
  "RE",
  "RES",
  "MI",
  "FA",
  "FAS",
  "SOL",
  "SOLS",
  "LA",
  "LAS",
  "SI",
  "SILENCIO",
  "MAYOR",
  "MENOR",
  "DIAG",
  "NUMEROS",
  "ID"
  };
}

